version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    depends_on:
      - db
    restart: on-failure
  db:
    build: ./db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure
volumes:
  logs: null
  postgresdb: null

networks:
  default:
    name: rsschool
    driver: bridge
